### ISSUE TITLE
Very Preliminary Draft Context

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#17] opened 2017-04-03 16:11 UTC
Feedback on this section below.

- Update this draft context to use https://w3id.org/xapi/ontology# instead of http://purl.org/xapi/ontology#

- Also, the context we’ve been using for vocab is here: http://xapi.vocab.pub/vocabulary/context.jsonld
Are there any issues with this?

- Should we have a separate context document for vocabulary than we do for profiles or should they be combined?

**Comment by fugu13** [comment] 2017-04-03 20:23
The vocabulary context will need fairly extensive revision for use in profiles -- many of the mappings will be different, even if only slightly, and there need to be a number of additional rules to ensure proper JSON-LD compaction. Almost all of the things that can be expressed in vocabularies can be expressed in profiles, and I think use of profiles will entirely subsume use of vocabularies. I'll go ahead and leave this and mark the existing draft context issue as a duplicate of this one.

**Comment by jhaag75** [comment] 2017-04-10 14:39
Agree that profiles could possibly subsume use of vocabularies but we need to discuss more deeply. We have several examples of terms that are associated with vocabularies such as ADL, Medbiq, TinCan, etc. For example, medbiq has a base vocabulary and several profiles they are creating that use that base vocabulary. I'm not sure if this would be the typical use case, but we should discuss how to improve disparate use cases to support the consistent practices for profiles moving forward. We also have all of the activity streams terms. So I guess the question is what profile do we associate terms with if they don't really belong to a profile? Do we need to support both? Should we roll up all of the old terms into a base xAPI vocabulary? Food for thought...

**Comment by fugu13** [comment] 2017-06-06 22:32
This isn't really an issue per se; closing

**Closed as completed by fugu13** 2017-06-06 22:32 UTC
